---
- hosts: client
  gather_facts: yes
  become: yes
  tasks:
    - name: Test ping
      ping:
    - name: Get ip
      command:
        cmd: ip a
- hosts: server
  gather_facts: yes
  become: yes
  tasks:
    - name: Test ping
      ping:
    - name: Get ip
      command:
        cmd: ip a

