---
- hosts: client
  tasks:
    - name: Test ping
      ping:
    - name: Get ip
      command:
        cmd: ip a
- hosts: server
  tasks:
    - name: Test ping
      ping:
    - name: Get ip
      command:
        cmd: ip a

