---
# handlers file for ansible-role-nginx
- name: start nginx
  systemd:
    name: nginx
    state: started
    enabled: true
- name: reload nginx
  systemd:
    name: nginx
    state: reloaded
- name: validate nginx
  command: nginx -t
  changed_when: false
- name: force run meta flush
  meta: flush_handlers
