---
# Define host
#- hosts: "{{hostname}}"
- hosts: nginx
# Get all information  
  gather_facts: true
# Root privileges
  become: yes
  roles:
    - role: external.nginx-roles
      vars:
        ansible_python_interpreter: "/usr/bin/python"
        nginx_status_enabled: "true"
  tasks:
  - name: Creates directry
    file:
      path: /var/www/nginx.svms.tk

      state: directory
  - name: 'copy file index'
    copy:
       src: /home/sonvh/Ansible-TOOA06/sonvh/index/
       dest: /var/www/nginx.svms.tk
       owner: root
       group: root
       mode: 0644
