---
- name: Remove sites-available and sites-enabled
  file:
    path: "{{item}}"
    state: absent
  with_items:
  - /etc/nginx/sites-available
  - /etc/nginx/sites-enable
- name: Override file nginx.conf
  template:
    src: "nginx.conf.j2"
    dest: "/etc/nginx/nginx.conf"
- name: Configure external vhosts
  copy:
    src: "{{vhost_directory}}"
    dest: "/etc/nginx/conf.d"
  when: force_use_external_vhost
  notify:
  - validate nginx
  - reload nginx
- name: force all notified handlers to run at this point, for applying all nginx configs
  meta: flush_handlers
